### ISSUE TITLE
Estimation of metrics per pixel

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/nadia#2]
Question from Aaron:
> I have another question about the SCT toolbox in general. I am currently using the pipeline to obtain metrics for each level of the spinal cord. Is there some way to obtain those DTI metrics for each voxel/pixel of the MRI? Thank you.

**Comment by jcohenadad** [comment]
What would be the purpose of extracting metric per voxel? Currently, the extraction method uses maximum a posteriori, which effectively reduces bias related to partial volume effect. This method is not compatible with per-voxel extraction.

**Comment by Aaronearlerichardson** [comment]
I am trying to build a machine learning algorithm that can detect demyelination. The problem I'm concerned with is that a training algorithm that averages over a cross sectional area may miss demyelination that takes up a very small portion of the entire cross section. Is there any way to split up the cross section into dorsal, ventral, left and right such that the MAP method can still effectively reduce spillover effects? Do you have any other suggestions?

**Comment by jcohenadad** [comment]
Absolutely. The cross-section ROI is specified with label `-l`. Please see usage: `sct_extract_metric -h`. For more documentation, please see the [latest SCT course](https://github.com/neuropoly/spinalcordtoolbox#courses). For questions not specific to this pipeline, but pertaining to SCT in general, please post in the [SCT forum](https://sourceforge.net/p/spinalcordtoolbox/discussion/help/). Thanks.

**Comment by Aaronearlerichardson** [comment]
Thank you! This is exactly what I was looking for. Also I will be sure to post any other questions on this forum in the future.
